spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5555/postgres
    username: university
    password: university
  flyway:
    enabled: true
    locations: classpath:db/migration
